export interface Institution {
  code: string;
  name: string;
  region: string;
}

export const REGIONS = [
  'Hà Nội',
  'TP.HCM',
  'Miền Bắc',
  'Miền Nam',
  'Miền Trung & Tây Nguyên',
  'Quân đội & Công an',
] as const;

export const INSTITUTIONS: Institution[] = [
  // ===== KHU VỰC HÀ NỘI =====
  { code: 'VNU', name: 'Đại học Quốc gia Hà Nội', region: 'Hà Nội' },
  { code: 'QHL', name: 'Khoa Luật (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'QHQ', name: 'Khoa Quốc tế (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'QHY', name: 'Trường ĐH Y Dược (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'QHI', name: 'Trường ĐH Công nghệ (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'QHE', name: 'Trường ĐH Kinh tế (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'QHS', name: 'Trường ĐH Giáo dục (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'QHT', name: 'Trường ĐH Khoa học Tự nhiên (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'QHX', name: 'Trường ĐH Khoa học Xã hội và Nhân văn (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'QHD', name: 'Trường Quản trị và kinh doanh (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'QHF', name: 'Trường ĐH Ngoại ngữ (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'VJU', name: 'Trường ĐH Việt Nhật (ĐHQG Hà Nội)', region: 'Hà Nội' },
  { code: 'NVH', name: 'Học viện Âm nhạc Quốc gia Việt Nam', region: 'Hà Nội' },
  { code: 'HBT', name: 'Học viện Báo chí Tuyên truyền', region: 'Hà Nội' },
  { code: 'HCP', name: 'Học viện Chính sách và Phát triển', region: 'Hà Nội' },
  { code: 'BVH', name: 'Học viện Công nghệ Bưu chính Viễn thông', region: 'Hà Nội' },
  { code: 'HCH', name: 'Học viện Hành chính Quốc gia', region: 'Hà Nội' },
  { code: 'KMA', name: 'Học viện Kỹ thuật Mật mã', region: 'Hà Nội' },
  { code: 'NHH', name: 'Học viện Ngân hàng', region: 'Hà Nội' },
  { code: 'HQT', name: 'Học viện Ngoại giao', region: 'Hà Nội' },
  { code: 'HVN', name: 'Học viện Nông nghiệp Việt Nam', region: 'Hà Nội' },
  { code: 'HPN', name: 'Học viện Phụ nữ Việt Nam', region: 'Hà Nội' },
  { code: 'HVQ', name: 'Học viện Quản lý Giáo dục', region: 'Hà Nội' },
  { code: 'HTC', name: 'Học viện Tài chính', region: 'Hà Nội' },
  { code: 'HTN', name: 'Học viện Thanh Thiếu niên Việt Nam', region: 'Hà Nội' },
  { code: 'HTA', name: 'Học viện Tòa án', region: 'Hà Nội' },
  { code: 'HYD', name: 'Học viện Y Dược học cổ truyền Việt Nam', region: 'Hà Nội' },
  { code: 'BKA', name: 'Đại học Bách khoa Hà Nội', region: 'Hà Nội' },
  { code: 'LDA', name: 'Trường ĐH Công đoàn', region: 'Hà Nội' },
  { code: 'GTA', name: 'Trường ĐH Công nghệ Giao thông vận tải', region: 'Hà Nội' },
  { code: 'CCM', name: 'Trường ĐH Công nghiệp Dệt may Hà Nội', region: 'Hà Nội' },
  { code: 'DCN', name: 'Trường ĐH Công nghiệp Hà Nội', region: 'Hà Nội' },
  { code: 'VHD', name: 'Trường ĐH Công nghiệp Việt Hung', region: 'Hà Nội' },
  { code: 'DDN', name: 'Trường ĐH Đại Nam', region: 'Hà Nội' },
  { code: 'DDL', name: 'Trường ĐH Điện lực', region: 'Hà Nội' },
  { code: 'DKH', name: 'Trường ĐH Dược Hà Nội', region: 'Hà Nội' },
  { code: 'FPT', name: 'Trường ĐH FPT', region: 'Hà Nội' },
  { code: 'GHA', name: 'Trường ĐH Giao thông vận tải', region: 'Hà Nội' },
  { code: 'NHF', name: 'Trường ĐH Hà Nội', region: 'Hà Nội' },
  { code: 'ETU', name: 'Trường ĐH Hòa Bình', region: 'Hà Nội' },
  { code: 'KCN', name: 'Trường ĐH Khoa học và Công nghệ Hà Nội', region: 'Hà Nội' },
  { code: 'DKS', name: 'Trường ĐH Kiểm sát Hà Nội', region: 'Hà Nội' },
  { code: 'KTA', name: 'Trường ĐH Kiến trúc Hà Nội', region: 'Hà Nội' },
  { code: 'DKK', name: 'Trường ĐH Kinh tế Kỹ thuật Công nghiệp', region: 'Hà Nội' },
  { code: 'KHA', name: 'Đại học Kinh tế Quốc dân', region: 'Hà Nội' },
  { code: 'LNH', name: 'Trường ĐH Lâm nghiệp', region: 'Hà Nội' },
  { code: 'DLX', name: 'Trường ĐH Lao động Xã hội', region: 'Hà Nội' },
  { code: 'LPH', name: 'Trường ĐH Luật Hà Nội', region: 'Hà Nội' },
  { code: 'MDA', name: 'Trường ĐH Mỏ Địa chất Hà Nội', region: 'Hà Nội' },
  { code: 'MTC', name: 'Trường ĐH Mỹ thuật Công nghiệp', region: 'Hà Nội' },
  { code: 'MTH', name: 'Trường ĐH Mỹ thuật Việt Nam', region: 'Hà Nội' },
  { code: 'NTH', name: 'Trường ĐH Ngoại thương', region: 'Hà Nội' },
  { code: 'NTU', name: 'Trường ĐH Nguyễn Trãi', region: 'Hà Nội' },
  { code: 'SKD', name: 'Trường ĐH Sân khấu Điện ảnh', region: 'Hà Nội' },
  { code: 'SPH', name: 'Trường ĐH Sư phạm Hà Nội', region: 'Hà Nội' },
  { code: 'GNT', name: 'Trường ĐH Sư phạm Nghệ thuật Trung ương', region: 'Hà Nội' },
  { code: 'TDH', name: 'Trường ĐH Sư phạm Thể dục thể thao Hà Nội', region: 'Hà Nội' },
  { code: 'FBU', name: 'Trường ĐH Tài chính Ngân hàng Hà Nội', region: 'Hà Nội' },
  { code: 'DMT', name: 'Trường ĐH Tài nguyên và Môi trường Hà Nội', region: 'Hà Nội' },
  { code: 'DTL', name: 'Trường ĐH Thăng Long', region: 'Hà Nội' },
  { code: 'TDD', name: 'Trường ĐH Thành Đô', region: 'Hà Nội' },
  { code: 'HNM', name: 'Trường ĐH Thủ đô Hà Nội', region: 'Hà Nội' },
  { code: 'TMU', name: 'Trường ĐH Thương mại', region: 'Hà Nội' },
  { code: 'TLA', name: 'Trường ĐH Thủy lợi', region: 'Hà Nội' },
  { code: 'VHH', name: 'Trường ĐH Văn hóa Hà Nội', region: 'Hà Nội' },
  { code: 'XDA', name: 'Trường ĐH Xây dựng Hà Nội', region: 'Hà Nội' },
  { code: 'YHB', name: 'Trường ĐH Y Hà Nội', region: 'Hà Nội' },
  { code: 'YTC', name: 'Trường ĐH Y tế Công cộng', region: 'Hà Nội' },
  { code: 'DCQ', name: 'Trường ĐH Công nghệ và Quản lý Hữu nghị', region: 'Hà Nội' },
  { code: 'DDU', name: 'Trường ĐH Đông Đô', region: 'Hà Nội' },
  { code: 'DQK', name: 'Trường ĐH Kinh doanh và Công nghệ Hà Nội', region: 'Hà Nội' },
  { code: 'DPD', name: 'Trường ĐH Phương Đông', region: 'Hà Nội' },
  { code: 'MHN', name: 'Trường ĐH Mở Hà Nội', region: 'Hà Nội' },
  { code: 'PKA', name: 'Đại học Phenikaa', region: 'Hà Nội' },
  { code: 'CMC', name: 'Trường ĐH CMC', region: 'Hà Nội' },

  // ===== KHU VỰC TP.HCM =====
  { code: 'VNU-HCM', name: 'Đại học Quốc gia TP.HCM', region: 'TP.HCM' },
  { code: 'QSY', name: 'Trường ĐH Sức khỏe - ĐHQG TP.HCM', region: 'TP.HCM' },
  { code: 'QSB', name: 'Trường ĐH Bách Khoa - ĐHQG TP.HCM', region: 'TP.HCM' },
  { code: 'QSC', name: 'Trường ĐH Công nghệ Thông tin - ĐHQG TP.HCM', region: 'TP.HCM' },
  { code: 'QST', name: 'Trường ĐH Khoa học Tự nhiên - ĐHQG TP.HCM', region: 'TP.HCM' },
  { code: 'QSX', name: 'Trường ĐH Khoa học Xã hội và Nhân văn - ĐHQG TP.HCM', region: 'TP.HCM' },
  { code: 'QSQ', name: 'Trường ĐH Quốc tế - ĐHQG TP.HCM', region: 'TP.HCM' },
  { code: 'QSK', name: 'Trường ĐH Kinh tế - Luật (ĐHQG TP.HCM)', region: 'TP.HCM' },
  { code: 'HVC', name: 'Học viện Cán bộ TP.HCM', region: 'TP.HCM' },
  { code: 'BVS', name: 'Học viện Công nghệ Bưu chính Viễn thông – CS TP.HCM', region: 'TP.HCM' },
  { code: 'HHK', name: 'Học viện Hàng không Việt Nam', region: 'TP.HCM' },
  { code: 'NVS', name: 'Nhạc viện TP.HCM', region: 'TP.HCM' },
  { code: 'DCT', name: 'Trường ĐH Công thương TP.HCM', region: 'TP.HCM' },
  { code: 'IUH', name: 'Trường ĐH Công nghiệp TP.HCM', region: 'TP.HCM' },
  { code: 'GSA', name: 'Trường ĐH Giao thông vận tải - Cơ sở 2', region: 'TP.HCM' },
  { code: 'GTS', name: 'Trường ĐH Giao thông vận tải TP.HCM', region: 'TP.HCM' },
  { code: 'HSU', name: 'Trường ĐH Hoa Sen', region: 'TP.HCM' },
  { code: 'KTS', name: 'Trường ĐH Kiến trúc TP.HCM', region: 'TP.HCM' },
  { code: 'UEF', name: 'Trường ĐH Kinh tế - Tài chính TP.HCM', region: 'TP.HCM' },
  { code: 'KSA', name: 'Đại học Kinh tế TP.HCM', region: 'TP.HCM' },
  { code: 'DLS', name: 'Trường ĐH Lao động Xã hội – CS TP.HCM', region: 'TP.HCM' },
  { code: 'LPS', name: 'Trường ĐH Luật TP.HCM', region: 'TP.HCM' },
  { code: 'MBS', name: 'Trường ĐH Mở TP.HCM', region: 'TP.HCM' },
  { code: 'MTS', name: 'Trường ĐH Mỹ thuật TP.HCM', region: 'TP.HCM' },
  { code: 'NHS', name: 'Trường ĐH Ngân hàng TP.HCM', region: 'TP.HCM' },
  { code: 'NTS', name: 'Trường ĐH Ngoại thương – CS phía Nam', region: 'TP.HCM' },
  { code: 'NTT', name: 'Trường ĐH Nguyễn Tất Thành', region: 'TP.HCM' },
  { code: 'NLS', name: 'Trường ĐH Nông Lâm TP.HCM', region: 'TP.HCM' },
  { code: 'HIU', name: 'Trường ĐH Quốc tế Hồng Bàng', region: 'TP.HCM' },
  { code: 'SGD', name: 'Trường ĐH Sài Gòn', region: 'TP.HCM' },
  { code: 'DSD', name: 'Trường ĐH Sân khấu Điện ảnh TP.HCM', region: 'TP.HCM' },
  { code: 'SPK', name: 'Trường ĐH Sư phạm Kỹ thuật TP.HCM', region: 'TP.HCM' },
  { code: 'SPS', name: 'Trường ĐH Sư phạm TP.HCM', region: 'TP.HCM' },
  { code: 'DMS', name: 'Trường ĐH Tài chính - Marketing', region: 'TP.HCM' },
  { code: 'DTM', name: 'Trường ĐH Tài nguyên và Môi trường TP.HCM', region: 'TP.HCM' },
  { code: 'TDS', name: 'Trường ĐH Thể dục Thể thao TP.HCM', region: 'TP.HCM' },
  { code: 'TLS', name: 'Trường ĐH Thủy lợi – Cơ sở 2', region: 'TP.HCM' },
  { code: 'DTT', name: 'Trường ĐH Tôn Đức Thắng', region: 'TP.HCM' },
  { code: 'VHS', name: 'Trường ĐH Văn hóa TP.HCM', region: 'TP.HCM' },
  { code: 'VGU', name: 'Trường ĐH Việt - Đức', region: 'TP.HCM' },
  { code: 'YDS', name: 'Trường ĐH Y Dược TP.HCM', region: 'TP.HCM' },
  { code: 'TYS', name: 'Trường ĐH Y khoa Phạm Ngọc Thạch', region: 'TP.HCM' },
  { code: 'DSG', name: 'Trường ĐH Công nghệ Sài Gòn', region: 'TP.HCM' },
  { code: 'GDU', name: 'Trường ĐH Gia Định', region: 'TP.HCM' },
  { code: 'DKC', name: 'Trường ĐH Công nghệ TP.HCM', region: 'TP.HCM' },
  { code: 'DHV', name: 'Trường ĐH Hùng Vương TP.HCM', region: 'TP.HCM' },
  { code: 'SIU', name: 'Trường ĐH Quốc tế Sài Gòn', region: 'TP.HCM' },
  { code: 'DVH', name: 'Trường ĐH Văn Hiến', region: 'TP.HCM' },
  { code: 'DVL', name: 'Trường ĐH Văn Lang', region: 'TP.HCM' },
  { code: 'STS', name: 'Trường ĐH Sư phạm TDTT TP.HCM', region: 'TP.HCM' },
  { code: 'DNT', name: 'Trường ĐH Ngoại ngữ - Tin học TP.HCM', region: 'TP.HCM' },
  { code: 'UMT', name: 'Trường ĐH Quản lý và Công nghệ TP.HCM', region: 'TP.HCM' },

  // ===== KHU VỰC MIỀN BẮC =====
  { code: 'TNU', name: 'Đại học Thái Nguyên', region: 'Miền Bắc' },
  { code: 'DTF', name: 'Trường Ngoại ngữ (ĐH Thái Nguyên)', region: 'Miền Bắc' },
  { code: 'DTQ', name: 'Khoa Quốc tế (ĐH Thái Nguyên)', region: 'Miền Bắc' },
  { code: 'DTP', name: 'Phân hiệu ĐH Thái Nguyên tại Lào Cai', region: 'Miền Bắc' },
  { code: 'DTC', name: 'Trường ĐH Công nghệ TT và Truyền thông (ĐH Thái Nguyên)', region: 'Miền Bắc' },
  { code: 'DTZ', name: 'Trường ĐH Khoa học (ĐH Thái Nguyên)', region: 'Miền Bắc' },
  { code: 'DTE', name: 'Trường ĐH Kinh tế - QTKD (ĐH Thái Nguyên)', region: 'Miền Bắc' },
  { code: 'DTK', name: 'Trường ĐH Kỹ thuật Công nghiệp (ĐH Thái Nguyên)', region: 'Miền Bắc' },
  { code: 'DTN', name: 'Trường ĐH Nông lâm (ĐH Thái Nguyên)', region: 'Miền Bắc' },
  { code: 'DTS', name: 'Trường ĐH Sư phạm (ĐH Thái Nguyên)', region: 'Miền Bắc' },
  { code: 'DTY', name: 'Trường ĐH Y Dược (ĐH Thái Nguyên)', region: 'Miền Bắc' },
  { code: 'DCA', name: 'Trường ĐH Chu Văn An', region: 'Miền Bắc' },
  { code: 'DDA', name: 'Trường ĐH Công nghệ Đông Á', region: 'Miền Bắc' },
  { code: 'DDM', name: 'Trường ĐH Công nghiệp Quảng Ninh', region: 'Miền Bắc' },
  { code: 'VUI', name: 'Trường ĐH Công nghiệp Việt Trì', region: 'Miền Bắc' },
  { code: 'DHP', name: 'Trường ĐH Quản lý và Công nghệ Hải Phòng', region: 'Miền Bắc' },
  { code: 'DTV', name: 'Trường ĐH Lương Thế Vinh', region: 'Miền Bắc' },
  { code: 'YDD', name: 'Trường ĐH Điều dưỡng Nam Định', region: 'Miền Bắc' },
  { code: 'HLU', name: 'Trường ĐH Hạ Long', region: 'Miền Bắc' },
  { code: 'DKT', name: 'Trường ĐH Hải Dương', region: 'Miền Bắc' },
  { code: 'THP', name: 'Trường ĐH Hải Phòng', region: 'Miền Bắc' },
  { code: 'HHA', name: 'Trường ĐH Hàng hải', region: 'Miền Bắc' },
  { code: 'DNB', name: 'Trường ĐH Hoa Lư', region: 'Miền Bắc' },
  { code: 'HDT', name: 'Trường ĐH Hồng Đức', region: 'Miền Bắc' },
  { code: 'THV', name: 'Trường ĐH Hùng Vương', region: 'Miền Bắc' },
  { code: 'UKB', name: 'Trường ĐH Kinh Bắc', region: 'Miền Bắc' },
  { code: 'DKY', name: 'Trường ĐH Kỹ thuật Y tế Hải Dương', region: 'Miền Bắc' },
  { code: 'DBG', name: 'Trường ĐH Nông Lâm Bắc Giang', region: 'Miền Bắc' },
  { code: 'DBH', name: 'Trường ĐH Quốc tế Bắc Hà', region: 'Miền Bắc' },
  { code: 'SDU', name: 'Trường ĐH Sao Đỏ', region: 'Miền Bắc' },
  { code: 'SP2', name: 'Trường ĐH Sư phạm Hà Nội 2', region: 'Miền Bắc' },
  { code: 'SKH', name: 'Trường ĐH Sư phạm Kỹ thuật Hưng Yên', region: 'Miền Bắc' },
  { code: 'SKN', name: 'Trường ĐH Sư phạm Kỹ thuật Nam Định', region: 'Miền Bắc' },
  { code: 'DFA', name: 'Trường ĐH Tài chính - Quản trị kinh doanh', region: 'Miền Bắc' },
  { code: 'TQU', name: 'Trường ĐH Tân Trào', region: 'Miền Bắc' },
  { code: 'TTB', name: 'Trường ĐH Tây Bắc', region: 'Miền Bắc' },
  { code: 'DTB', name: 'Trường ĐH Thái Bình', region: 'Miền Bắc' },
  { code: 'DDB', name: 'Trường ĐH Thành Đông', region: 'Miền Bắc' },
  { code: 'TDB', name: 'Trường ĐH Thể dục Thể thao Bắc Ninh', region: 'Miền Bắc' },
  { code: 'DVP', name: 'Trường ĐH Trưng Vương', region: 'Miền Bắc' },
  { code: 'DVD', name: 'Trường ĐH Văn hóa Thể thao và Du lịch Thanh Hóa', region: 'Miền Bắc' },
  { code: 'DVB', name: 'Trường ĐH Việt Bắc', region: 'Miền Bắc' },
  { code: 'YPB', name: 'Trường ĐH Y Dược Hải Phòng', region: 'Miền Bắc' },
  { code: 'YTB', name: 'Trường ĐH Y Dược Thái Bình', region: 'Miền Bắc' },
  { code: 'THU', name: 'Trường ĐH Y khoa Tokyo Việt Nam', region: 'Miền Bắc' },

  // ===== KHU VỰC MIỀN NAM =====
  { code: 'TAG', name: 'Đại học Cần Thơ', region: 'Miền Nam' },
  { code: 'BVU', name: 'Trường ĐH Bà Rịa - Vũng Tàu', region: 'Miền Nam' },
  { code: 'DBL', name: 'Trường ĐH Bạc Liêu', region: 'Miền Nam' },
  { code: 'DBD', name: 'Trường ĐH Bình Dương', region: 'Miền Nam' },
  { code: 'TCT', name: 'Trường ĐH An Giang (ĐHQG HCM)', region: 'Miền Nam' },
  { code: 'DCD', name: 'Trường ĐH Công nghệ Đồng Nai', region: 'Miền Nam' },
  { code: 'MIT', name: 'Trường ĐH Công nghệ Miền Đông', region: 'Miền Nam' },
  { code: 'DCL', name: 'Trường ĐH Cửu Long', region: 'Miền Nam' },
  { code: 'DLH', name: 'Trường ĐH Lạc Hồng', region: 'Miền Nam' },
  { code: 'PVU', name: 'Trường ĐH Dầu khí Việt Nam', region: 'Miền Nam' },
  { code: 'DNU', name: 'Trường ĐH Đồng Nai', region: 'Miền Nam' },
  { code: 'SPD', name: 'Trường ĐH Đồng Tháp', region: 'Miền Nam' },
  { code: 'TKG', name: 'Trường ĐH Kiên Giang', region: 'Miền Nam' },
  { code: 'DLA', name: 'Trường ĐH Kinh tế Công nghiệp Long An', region: 'Miền Nam' },
  { code: 'DKB', name: 'Trường ĐH Kinh tế Kỹ thuật Bình Dương', region: 'Miền Nam' },
  { code: 'KCC', name: 'Trường ĐH Kỹ thuật Công nghệ Cần Thơ', region: 'Miền Nam' },
  { code: 'LNS', name: 'Trường ĐH Lâm nghiệp – Cơ sở 2', region: 'Miền Nam' },
  { code: 'DNC', name: 'Trường ĐH Nam Cần Thơ', region: 'Miền Nam' },
  { code: 'EIU', name: 'Trường ĐH Quốc tế Miền Đông', region: 'Miền Nam' },
  { code: 'VLU', name: 'Trường ĐH Sư phạm Kỹ thuật Vĩnh Long', region: 'Miền Nam' },
  { code: 'TTU', name: 'Trường ĐH Tân Tạo', region: 'Miền Nam' },
  { code: 'DTD', name: 'Trường ĐH Tây Đô', region: 'Miền Nam' },
  { code: 'TDM', name: 'Trường ĐH Thủ Dầu Một', region: 'Miền Nam' },
  { code: 'TTG', name: 'Trường ĐH Tiền Giang', region: 'Miền Nam' },
  { code: 'DVT', name: 'Trường ĐH Trà Vinh', region: 'Miền Nam' },
  { code: 'VGU2', name: 'Trường ĐH Việt – Đức (CS2)', region: 'Miền Nam' },
  { code: 'VTT', name: 'Trường ĐH Võ Trường Toản', region: 'Miền Nam' },
  { code: 'MTU', name: 'Trường ĐH Xây dựng Miền Tây', region: 'Miền Nam' },
  { code: 'YCT', name: 'Trường ĐH Y Dược Cần Thơ', region: 'Miền Nam' },

  // ===== KHU VỰC MIỀN TRUNG & TÂY NGUYÊN =====
  { code: 'HueUni', name: 'Đại học Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHD', name: 'Trường Du lịch - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHC', name: 'Khoa Giáo dục Thể chất - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHT', name: 'Trường ĐH Khoa học - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHK', name: 'Trường ĐH Kinh tế - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHL', name: 'Trường ĐH Nông Lâm - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHN', name: 'Trường ĐH Nghệ thuật - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHA', name: 'Trường ĐH Luật - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHF', name: 'Trường ĐH Ngoại ngữ - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHS', name: 'Trường ĐH Sư phạm - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHY', name: 'Trường ĐH Y Dược - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHE', name: 'Khoa Kỹ thuật và Công nghệ - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHI', name: 'Khoa Quốc tế - ĐH Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DHQ', name: 'Phân hiệu ĐH Huế tại Quảng Trị', region: 'Miền Trung & Tây Nguyên' },
  { code: 'UDN', name: 'Đại học Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DDG', name: 'Khoa Giáo dục Thể chất – ĐH Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DDY', name: 'Khoa Y Dược – ĐH Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DDP', name: 'Phân hiệu ĐH Đà Nẵng tại Kon Tum', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DDK', name: 'Trường ĐH Bách Khoa - ĐH Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DDQ', name: 'Trường ĐH Kinh tế - ĐH Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DDF', name: 'Trường ĐH Ngoại ngữ - ĐH Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DDS', name: 'Trường ĐH Sư phạm - ĐH Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DSK', name: 'Trường ĐH Sư phạm Kỹ thuật – ĐH Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DDV', name: 'Viện nghiên cứu đào tạo Việt - Anh - ĐH Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'VKU', name: 'Khoa CNTT và Truyền thông – ĐH Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'KTD', name: 'Trường ĐH Kiến trúc Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'BMU', name: 'Trường ĐH Y dược Buôn Ma Thuột', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DVX', name: 'Trường ĐH Công nghệ Vạn Xuân', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DCV', name: 'Trường ĐH Công nghiệp Vinh', region: 'Miền Trung & Tây Nguyên' },
  { code: 'TDL', name: 'Trường ĐH Đà Lạt', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DDT', name: 'Đại học Duy Tân', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DPX', name: 'Trường ĐH Phú Xuân', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DYD', name: 'Trường ĐH Yersin Đà Lạt', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DAD', name: 'Trường ĐH Đông Á', region: 'Miền Trung & Tây Nguyên' },
  { code: 'HHT', name: 'Trường ĐH Hà Tĩnh', region: 'Miền Trung & Tây Nguyên' },
  { code: 'UKH', name: 'Trường ĐH Khánh Hòa', region: 'Miền Trung & Tây Nguyên' },
  { code: 'CEA', name: 'Trường ĐH Kinh tế Nghệ An', region: 'Miền Trung & Tây Nguyên' },
  { code: 'YDN', name: 'Trường ĐH Kỹ thuật Y Dược Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'HVA', name: 'Học viện Âm nhạc Huế', region: 'Miền Trung & Tây Nguyên' },
  { code: 'TSN', name: 'Trường ĐH Nha Trang', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DPQ', name: 'Trường ĐH Phạm Văn Đồng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DPC', name: 'Trường ĐH Phan Châu Trinh', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DPT', name: 'Trường ĐH Phan Thiết', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DPY', name: 'Trường ĐH Phú Yên', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DQB', name: 'Trường ĐH Quảng Bình', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DQU', name: 'Trường ĐH Quảng Nam', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DQT', name: 'Trường ĐH Quang Trung', region: 'Miền Trung & Tây Nguyên' },
  { code: 'DQN', name: 'Trường ĐH Quy Nhơn', region: 'Miền Trung & Tây Nguyên' },
  { code: 'SKV', name: 'Trường ĐH Sư phạm Kỹ thuật Vinh', region: 'Miền Trung & Tây Nguyên' },
  { code: 'UFA', name: 'Trường ĐH Tài chính Kế toán', region: 'Miền Trung & Tây Nguyên' },
  { code: 'TTN', name: 'Trường ĐH Tây Nguyên', region: 'Miền Trung & Tây Nguyên' },
  { code: 'TBD', name: 'Trường ĐH Thái Bình Dương', region: 'Miền Trung & Tây Nguyên' },
  { code: 'TTD', name: 'Trường ĐH Thể dục Thể thao Đà Nẵng', region: 'Miền Trung & Tây Nguyên' },
  { code: 'TDV', name: 'Trường ĐH Vinh', region: 'Miền Trung & Tây Nguyên' },
  { code: 'XDT', name: 'Trường ĐH Xây dựng Miền Trung', region: 'Miền Trung & Tây Nguyên' },
  { code: 'YKV', name: 'Trường ĐH Y khoa Vinh', region: 'Miền Trung & Tây Nguyên' },

  // ===== QUÂN ĐỘI & CÔNG AN =====
  { code: 'BPH', name: 'Học viện Biên phòng', region: 'Quân đội & Công an' },
  { code: 'HQH', name: 'Học viện Hải Quân', region: 'Quân đội & Công an' },
  { code: 'HEH', name: 'Học viện Hậu cần', region: 'Quân đội & Công an' },
  { code: 'NQH', name: 'Học viện Khoa học Quân sự', region: 'Quân đội & Công an' },
  { code: 'KQH', name: 'Học viện Kỹ thuật Quân sự', region: 'Quân đội & Công an' },
  { code: 'PKH', name: 'Học viện Phòng không - Không quân', region: 'Quân đội & Công an' },
  { code: 'YQH', name: 'Học viện Quân Y', region: 'Quân đội & Công an' },
  { code: 'LCH', name: 'Trường Sĩ quan Chính trị', region: 'Quân đội & Công an' },
  { code: 'ZNH', name: 'Trường ĐH Văn hóa - Nghệ thuật Quân đội', region: 'Quân đội & Công an' },
  { code: 'SNH', name: 'Trường Sĩ quan Công binh', region: 'Quân đội & Công an' },
  { code: 'DCH', name: 'Trường Sĩ quan Đặc công', region: 'Quân đội & Công an' },
  { code: 'KGH', name: 'Trường Sĩ quan Không quân', region: 'Quân đội & Công an' },
  { code: 'VPH', name: 'Trường Sĩ quan Kỹ thuật QS Vinhempich', region: 'Quân đội & Công an' },
  { code: 'LAH', name: 'Trường Sĩ quan Lục quân 1', region: 'Quân đội & Công an' },
  { code: 'LBH', name: 'Trường Sĩ quan Lục quân 2', region: 'Quân đội & Công an' },
  { code: 'PBH', name: 'Trường Sĩ quan Pháo binh', region: 'Quân đội & Công an' },
  { code: 'HGH', name: 'Trường Sĩ quan Phòng Hóa', region: 'Quân đội & Công an' },
  { code: 'TGH', name: 'Trường Sĩ quan Tăng - Thiết giáp', region: 'Quân đội & Công an' },
  { code: 'TTH', name: 'Trường Sĩ quan Thông tin', region: 'Quân đội & Công an' },
  { code: 'ANH', name: 'Học viện An ninh Nhân dân', region: 'Quân đội & Công an' },
  { code: 'CSH', name: 'Học viện Cảnh sát Nhân dân', region: 'Quân đội & Công an' },
  { code: 'HCA', name: 'Học viện Chính trị Công an Nhân dân', region: 'Quân đội & Công an' },
  { code: 'ANS', name: 'Trường ĐH An ninh nhân dân', region: 'Quân đội & Công an' },
  { code: 'CSS', name: 'Trường ĐH Cảnh sát nhân dân', region: 'Quân đội & Công an' },
  { code: 'HCB', name: 'Trường ĐH Kỹ thuật - Hậu cần CAND phía Bắc', region: 'Quân đội & Công an' },
  { code: 'HCN', name: 'Trường ĐH Kỹ thuật - Hậu cần CAND phía Nam', region: 'Quân đội & Công an' },
  { code: 'PCH', name: 'Trường ĐH Phòng cháy chữa cháy phía Bắc', region: 'Quân đội & Công an' },
  { code: 'PCS', name: 'Trường ĐH Phòng cháy chữa cháy phía Nam', region: 'Quân đội & Công an' },
];

/** Remove Vietnamese diacritics for search */
function removeDiacritics(str: string): string {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/Đ/g, 'D');
}

/** Search institutions by name or code */
export function searchInstitutions(query: string): Institution[] {
  if (!query.trim()) return INSTITUTIONS;
  const q = removeDiacritics(query.toLowerCase().trim());
  return INSTITUTIONS.filter(inst => {
    const name = removeDiacritics(inst.name.toLowerCase());
    const code = inst.code.toLowerCase();
    return name.includes(q) || code.includes(q);
  });
}

/** Get institutions grouped by region */
export function getInstitutionsByRegion(): Map<string, Institution[]> {
  const map = new Map<string, Institution[]>();
  for (const region of REGIONS) {
    map.set(region, INSTITUTIONS.filter(i => i.region === region));
  }
  return map;
}
